version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 3s
      retries: 10
  
  auction-svc:
    image: maju84/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctiondb
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  search-svc:
    image: maju84/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
    ports:
      - 7002:80
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  identity-svc:
    image: maju84/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identitydb
    ports:
      - 80:80
    depends_on:
      postgres:
        condition: service_healthy

  gateway-svc:
    image: maju84/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

  bid-svc:
    image: maju84/bid-svc:latest
    build: 
      context: .
      dockerfile: src/BidService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuctionServiceUrl=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      auction-svc:
        condition: service_started

  notification-svc:
    image: maju84/notification-svc:latest
    build: 
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  wheeldealz-fe:
    image: maju84/wheeldealz-fe:latest
    build: 
      context: .
      dockerfile: frontend/wheeldealz-fe/Dockerfile
    volumes:
      - /var/lib/web/data   # for a cache. no need to persist between restarts
    ports:
      - 3000:3000
    links:
      - identity-svc:identity.wheeldealz.tech
    environment:
      - NEXTAUTH_SECRET=somethingsupersecret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://wheeldealz-fe:3000
      - API_URL=http://gateway-svc/
      - IDENTITY_SERVER_URL=http://identity.wheeldealz.tech
      - NEXT_PUBLIC__NOTIFICATIONS_URL=http://gateway-svc/notifications

    depends_on:
      auction-svc:
        condition: service_started
      search-svc:
        condition: service_started
      bid-svc:
        condition: service_started
      notification-svc:
        condition: service_started
      identity-svc:
        condition: service_started


volumes:
  pgdata:
  mongodata:
