apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: maju84/bid-svc
        imagePullPolicy: Always
        env:
          - name: RabbitMq__Host
            value: rabbitmq-clusterip
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: bid-svc-secret
                key: rabbitUser
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: bid-svc-secret
                key: rabbitPassword
          - name: ConnectionStrings__BidDbConnection
            valueFrom:
              secretKeyRef:
                name: bid-svc-secret
                key: connString
          - name: IdentityServiceUrl
            value: https://identity.more-than.tech
          - name: GrpcAuctionServiceUrl
            value: http://auction-svc-clusterip:7777

---

apiVersion: v1
kind: Service
metadata:
  name: bid-svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 8080
