apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheeldealz-fe
spec:
  selector:
    matchLabels:
      app: wheeldealz-fe
  template:
    metadata:
      labels:
        app: wheeldealz-fe
    spec:
      containers:
      - name: wheeldealz-fe
        image: maju84/wheeldealz-fe
        imagePullPolicy: Always
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: wheeldealz-fe-secret
                key: authSecret
          - name: NEXTAUTH_URL
            value: https://app.wheeldealz.tech
          - name: API_URL
            value: http://gateway-svc-clusterip/
          - name: IDENTITY_SERVER_URL
            value: https://identity.more-than.tech
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: wheeldealz-fe-clusterip
spec:
  type: ClusterIP
  selector:
    app: wheeldealz-fe
  ports:
  - port: 3000
    targetPort: 3000
