apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: 'postgres-secret-pw'  # special chars within single quotes ('')
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  username: rabbit-username
  password: rabbit-secret-pw
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  username: mongo-username
  password: mongo-secret-pw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-svc-secret
type: Opaque
stringData:
  connString: 'Server=postgres-clusterip:5432;User Id=postgres;Password=postgres-secret-pw;Database=auctiondb'
  rabbitUser: rabbit-username
  rabbitPassword: rabbit-secret-pw
---
apiVersion: v1
kind: Secret
metadata:
  name: search-svc-secret
type: Opaque
stringData:
  connString: 'mongodb://mongo-username:mongo-secret-pw@mongodb-clusterip'
  rabbitUser: rabbit-username 
  rabbitPassword: rabbit-secret-pw
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-svc-secret
type: Opaque
stringData:
  rabbitUser: rabbit-username 
  rabbitPassword: rabbit-secret-pw
---
apiVersion: v1
kind: Secret
metadata:
  name: wheeldealz-fe-secret
type: Opaque
stringData:
  authSecret: sosecretitreallyhurts
  clientSecret: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: bid-svc-secret
type: Opaque
stringData:
  connString: 'mongodb://mongo-username:mongo-secret-pw@mongodb-clusterip'
  rabbitUser: rabbit-username 
  rabbitPassword: rabbit-secret-pw
  