name: deploy-wheeldealz-fe

on:
  workflow_dispatch:  # allows to run this workflow manually
  push:
    branches:  [ "main" ]
    paths:
      - 'frontend/wheeldealz-fe/**'

env:
  REGISTRY_IMAGE_NAME: wheeldealz-fe
  DEPLOYMENT_NAME: wheeldealz-fe
  DOCKERFILE_PATH: ./frontend/wheeldealz-fe/Dockerfile
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}"
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REGISTRY_IMAGE_NAME }}:latest

    - name: Install doctl
      if: success()
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      if: success()
      run: doctl kubernetes cluster kubeconfig save wheeldealz

    - name: Restart Deployment
      if: success()
      run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}

      
