name: deploy-bid-svc

on:
  workflow_dispatch:  # allows to run this workflow manually
  push:
    branches:  [ "main", "feature/k8s-do" ]
    paths:
      - 'src/BidService/**'

env:
  REGISTRY_IMAGE_NAME: bid-svc
  DEPLOYMENT_NAME: bid-svc
  DOCKERFILE_PATH: ./src/BidService/Dockerfile
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REGISTRY_IMAGE_NAME }}:latest

    - name: Install doctl
      if: success()
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      if: success()
      run: doctl kubernetes cluster kubeconfig save wheeldealz

    - name: Restart Deployment
      if: success()
      run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}

      
