name: publish-identity-svc

on:
  workflow_dispatch:  # Allows you to run this workflow manually
  push:
    branches:  [ "main" ] #  , "feature/k8s-local" ]
    paths:
      - 'src/IdentityService/**'  # only for changes on the IdentityService

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3 # as we are using Dockerfile inside a subfolder

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/IdentityService/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/identity-svc:latest

      
